spring:

  application:
    name: Rental-Tool-Management
  h2:
    console:
      enabled: true
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tools?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: password
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: true
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  cache:
    type: simple

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

resilience4j.circuitbreaker:
  instances:
    rentalService:
      register-health-indicator: true
      sliding-window-size: 5
      minimum-number-of-calls: 3
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10000ms

#  security:
#    user:
#      name: admin        #  admin username
#      password: securepass  #  admin password (use strong password )


#spring:
#  profiles:
#    active: dev  # Change to 'prod' for production
